apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-father
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/lmelec/argocd-hands-on.git
    targetRevision: HEAD
    path: ./app-of-apps/apps

    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
  
