apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-declarative
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./simple-app-declarative/manifest
    repoURL: 'https://github.com/lmelec/argocd-hands-on.git'
    targetRevision: HEAD
  sources: []
  project: default
